### ISSUE TITLE
microlens-contra is not needed with GHC HEAD

### ISSUE THREAD

**Issue by neongreen** [monadfix/microlens#102]
Contravariant has been moved to base (hooray)

**Comment by neongreen** [comment]
I have released `microlens-contra-0.1.0.2` which doesn't depend on `contravariant` starting from GHC 8.6. I'm not sure whether I should conditionally export true `Getter` and `Fold` from `microlens` proper -- any advice?

**Comment by fosskers** [comment]
My gut says "yes", although you'd have to be careful / restrictive with `base` bounds.

**Comment by neongreen** [comment]
Created #116 and #117.
