### ISSUE TITLE
Should (#.) be marked INLINE?

### ISSUE THREAD

**Issue by jwiegley** [monadfix/microlens#106]
I ask because I'm seeing `#.` take up 14% of the execution time in my profile output, and noticed that I have no real option of forcing it to be inlined.

**Comment by jwiegley** [comment]
I tried adding `INLINE` in a private clone of the library, and it resulted a fairly significant speedup in my case (nearly 2x).

**Comment by neongreen** [comment]
Looks like they should be, yes.

**Comment by neongreen** [comment]
I'll fix it in a jiffy.

**Comment by neongreen** [comment]
Okay, I have no idea how it happened, but luckily it's fixed now. Thanks for the report!

These versions (already on Hackage) contain the fix:

* microlens-0.4.10
* microlens-ghc-0.4.10
* microlens-platform-0.3.11

I will add [inspection tests](http://hackage.haskell.org/package/inspection-testing) and see if there are other omissions like that lurking around.

**Comment by jwiegley** [comment]
Thank you!
