### ISSUE TITLE
Feedback needed: deprecating microlens-ghc

### ISSUE THREAD

**Issue by neongreen** [monadfix/microlens#113]
> ### microlens-ghc: microlens + array, bytestring, containers, transformers
>
> Use this package instead of microlens if you don't mind depending on all dependencies here – `Lens.Micro.GHC` reexports everything from `Lens.Micro` and additionally provides orphan instances of microlens classes for packages coming with GHC (array, bytestring, containers, transformers).

`microlens-ghc` has only 4 reverse dependencies (`microlens` has 120+, `microlens-platform` and `microlens-th` have ~40).

I propose deprecating `microlens-ghc` and moving the instances contained there into `microlens-platform`.

**Comment by neongreen** [comment]
Alternatively, I could move the instances into `microlens` itself 🤔

**Comment by fosskers** [comment]
Looks like my `aura` depends on `microlens-ghc`, but I imagine that everything in the dep graph of `microlens-platform` is probably already in Aura, so the move probably wouldn't affect me much.

**Comment by neongreen** [comment]
Given this and Twitter feedback, I have decided to move the instances into microlens-platform.
