### ISSUE TITLE
Zoom constraint excludes FreeT instance

### ISSUE THREAD

**Issue by treeowl** [monadfix/microlens#120]
`lens` includes a `Zoom` instance for `FreeT`. It's a rather complicated instance, and it does not satisfy the requirement that `Zoomed (FreeT f m) ~ Zoomed (FreeT f n)`, even when `Zoomed m ~ Zoomed n`. Does that extra equality constraint (not found in `lens`) actually help much? If not, perhaps it should be removed. I don't see any obvious way to take advantage of the constraint.

**Comment by neongreen** [comment]
The constraint was removed from `lens` in https://github.com/ekmett/lens/pull/645. I will remove it from `microlens` and write a comment in this issue when there's a new release available.

**Comment by neongreen** [comment]
Fixed in [microlens-mtl-0.2.0](http://hackage.haskell.org/package/microlens-mtl-0.2.0).

**Comment by treeowl** [comment]
Thanks!
