### ISSUE TITLE
[GHC 9] Port TH changes

### ISSUE THREAD

**Issue by neongreen** [monadfix/microlens#134]
https://github.com/ekmett/lens/commit/6a2e47aefb8400c2f6f74b14cdf6cfa3abf675e7

**Comment by recursion-ninja** [comment]
`microlens-th` as a transitive dependency is blocking my ability to test `ghc-9.0-rc1`. My appreciation for new version of with compatibility with `ghc-9.0` cannot be overstated!

**Comment by neongreen** [comment]
Ok, just wait till Nix builds GHC 9 on my machine

**Comment by neongreen** [comment]
@recursion-ninja Released a new version.
