### ISSUE TITLE
Drop support for GHC < 7.9 and base < 4.8?

### ISSUE THREAD

**Issue by sjshuck** [monadfix/microlens#150]
Asking because my PR (#148) failed to CI.  I used `traverse` but didn't import them from `Data.Traversable`.

Before I commit more CPP, I figured I'd ask what plans you have in mind.

**Comment by neongreen** [comment]
The min supported version is 7.6

**Comment by sjshuck** [comment]
Thanks.  My fault - I wasn't clear at all in my question.  I wanted to know what your plan is for GHC and base versions going forward.  (I don't really have a strong opinion.)

In the meantime I'll fix my PR for old GHC+base.

**Comment by neongreen** [comment]
The plan is to keep compat with 7.6 unless it becomes prohibitively expensive. I think we already had to drop compat with 7.4 but I don't remember why anymore.
